spring:
  application:
    name: all-demo
  rabbitmq:
    host: 101.133.170.33
    username: guest
    password: guest
    virtual-host: /ems
    publisher-confirm-type: correlated #开启发布确认
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300 # es的连接地址及端口号
      cluster-name: elasticsearch # es集群的名称




