name: Juejin Auto Sign In

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行

jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run sign in script
      env:
        JUEJIN_COOKIE: ${{ secrets.JUEJIN_COOKIE }}
      run: |
        python sign_in.py
